# Array Creation Functions 

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [4]:
b=np.arange(0,10,3)  #values from 0 to 10 with step 2
print("Array b:",b)

Array b: [0 3 6 9]


In [5]:
d=np.zeros((2,3))   # 2*3 array of zeros
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
d=np.zeros((2,3),dtype=int)
print("Array d:\n",d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [7]:
e=np.ones((3,2),dtype=int)
print("Array e:\n",e)

Array e:
 [[1 1]
 [1 1]
 [1 1]]


In [8]:
e=np.ones((3,2))
print("Array e:\n",e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
f=np.eye(4)   # 4*4 identity matrix
print("Tdentity matrix f:\n",f)

Tdentity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Manipulation Functions 

In [10]:
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3))  reshape to 1*3
print("Reshaped array:",reshaped)

SyntaxError: invalid syntax (2978704380.py, line 2)

In [11]:
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(3,1))
print("Reshaped array:",reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [12]:
f1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened=np.ravel(f1)   # Flattened to 1D array
print("Flattened array:",flattened)

Flattened array: [ 1  2  3  4  5  6  7  8  9 10]


In [13]:
e1=np.array([[1,2],[3,4]])
transposed=np.transpose(e1)  # Transpose the array
print("Transposed array:\n",transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [14]:
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2])  #stack a and b vertically
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [15]:
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.hstack([a2,b2])
print("Stacked arrays:\n",stacked)  # stack a and b horizontal

Stacked arrays:
 [1 2 3 4]


# Mathmatical Functions 

In [16]:
g=np.array([1,2,3,4])
added=np.add(g,2)
print("Added 2 to g:",added)  # added 2 element

Added 2 to g: [3 4 5 6]


In [17]:
squared=np.power(g,2)
print("Squared g:",squared)  # sqaure each element

Squared g: [ 1  4  9 16]


In [18]:
sqrt_val=np.sqrt(g)
print("Square root of g",sqrt_val)  # square root of each elemnt

Square root of g [1.         1.41421356 1.73205081 2.        ]


In [19]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [20]:
a3=np.array([1,2,3])
dot_product=np.dot(a,g)  #Dot product a and g
print("Dot product of a1 and a:",dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [21]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [22]:
a3=np.array([1,2,3])
dot_product=np.dot(a1,a)
print("Dot product of a1 and a:",dot_product)

Dot product of a1 and a: 14


# Statistical Functions 

In [23]:
s=np.array([1,2,3,4])
mean=np.mean(s)   
print("Mean of s:",mean)

Mean of s: 2.5


In [24]:
# standard deviation of array
var= np.var(s)
print("Variance of s:",var)

Variance of s: 1.25


In [25]:
# standard deviation of array
std_dev=np.std(s)
print("Standard deviation of s:",std_dev)

Standard deviation of s: 1.118033988749895


In [26]:
minimum=np.min(s)
print("Min of s:",minimum)

Min of s: 1


In [27]:
maximum=np.max(s)
print("Max of s:",maximum)

Max of s: 4


# Linear Algebra Functions 

In [29]:
matrix=np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

# Random Sampling Functions 

In [35]:
random_vals=np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.58857644 0.25408247 0.63164238]


In [36]:
np.random.seed(0)
random_vals=np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [42]:
rand_ints=np.random.randint(0,10,size=4)
print("Random integers:",rand_ints)

Random integers: [9 3 5 2]


In [41]:
np.random.seed(0)
rand_ints=np.random.randint(0,10,size=5)
print("Random integers:",rand_ints)

Random integers: [5 0 3 3 7]


# Boolean & Logical Functions 

In [30]:
logical_test=np.array([True, False, True])
all_true=np.all(logical_test)
print("All elements True:",all_true)

All elements True: False


In [31]:
logical_test=np.array([True, False, True])
all_true=np.all(logical_test)
print("All elements True:", all_true)

All elements True: False


In [33]:
logical_test=np.array([False, False, False])
all_true=np.all(logical_test)
print("All elements True:", all_true)

All elements True: False


In [34]:
any_true=np.any(logical_test)
print("Any elements True:", any_true)

Any elements True: False


# Set Operations 

In [35]:
set_a=np.array([1,2,3,4])
set_b=np.array([3,4,5,6])
intersection=np.intersect1d(set_a, set_b)
print("Intersection of a and b:",intersection)

Intersection of a and b: [3 4]


In [36]:
union=np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# Array Attribute Functions 

In [38]:
a=np.array([1,2,3])
shape=a.shape
size=a.size
dimensions=a.ndim
dtype=a.dtype

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


# Other Functions 

In [39]:
a=np.array([1,2,3])
copied_array=np.array(a)
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [40]:
a

array([1, 2, 3])

In [42]:
array_size_in_bytes=a.nbytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [45]:
shared=np.shares_memory(a,copied_array)
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
